# Generated by Django 2.1.7 on 2019-05-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_from_country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
