# Generated by Django 2.1.7 on 2019-03-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
