# Generated by Django 2.1.7 on 2019-05-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_id',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
