# Generated by Django 2.1.7 on 2019-04-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20190415_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile-images')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=1000, null=True)),
                ('places_been', models.TextField(blank=True, null=True)),
                ('places_to', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
