# Generated by Django 2.1.7 on 2019-04-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='profile-images'),
        ),
    ]
