# Generated by Django 2.1.7 on 2019-03-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20190316_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=150)),
                ('continent', models.CharField(choices=[('asia', 'Asia'), ('africa', 'Africa'), ('north america', 'North America'), ('south america', 'South America'), ('antarctica', 'ANTARCTICA'), ('europe', 'Europe'), ('australia', 'Australia')], max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=150)),
                ('when', models.DateField()),
                ('user', models.ManyToManyField(to='accounts.User')),
            ],
        ),
    ]
