# Generated by Django 2.1.7 on 2019-03-20 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=150, null=True)),
                ('continent', models.CharField(choices=[('asia', 'Asia'), ('africa', 'Africa'), ('north america', 'North America'), ('south america', 'South America'), ('antarctica', 'ANTARCTICA'), ('europe', 'Europe'), ('australia', 'Australia')], max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations')),
                ('town', models.CharField(max_length=150)),
                ('start', models.DateField(default=datetime.datetime.now)),
                ('end', models.DateField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.User')),
                ('users', models.ManyToManyField(related_name='candidates', to='accounts.User')),
            ],
        ),
    ]
