# Generated by Django 2.1.7 on 2019-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='unique_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
