# Generated by Django 2.1.1 on 2019-03-20 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20190319_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='when',
            new_name='end',
        ),
        migrations.AddField(
            model_name='adventure',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
