# Generated by Django 2.1.7 on 2019-05-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_following'),
        ('travel', '0004_auto_20190525_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='accounts.User'),
            preserve_default=False,
        ),
    ]
