# Generated by Django 2.1.7 on 2019-05-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_following'),
        ('travel', '0006_auto_20190525_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination_comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='destination_comment',
            name='name',
        ),
        migrations.AddField(
            model_name='destination_comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
