# Generated by Django 2.1.7 on 2019-05-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20190525_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination_comment',
            options={'ordering': ['-created']},
        ),
    ]
