# Generated by Django 2.1.7 on 2019-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20190526_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='commentaries',
            field=models.TextField(blank=True, null=True),
        ),
    ]
