# Generated by Django 2.1.7 on 2019-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_adventure_commentaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='popuular',
            field=models.BooleanField(default=False),
        ),
    ]
